set(OpenCV_ROOT ${EXT_INSTALL_PATH}/opencv CACHE INTERNAL "")

ExternalProject_Add(opencv
    SOURCE_DIR ${CMAKE_SOURCE_DIR}/3rd_party/opencv
    CMAKE_ARGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR} -DWITH_IPP=${WITH_IPP} -DWITH_OPENCL=${WITH_OPENCL} -DWITH_OPENMP=${WITH_OPENMP}
    INSTALL_COMMAND make install
)

list(APPEND GLOBAL_THIRDPARTY_LIB_ARGS "-DOpenCV_ROOT:PATH=${OpenCV_ROOT}")
